import cell from './images/cell.png'

const product = [
{
  id: 1,
  image: cell,
  tittle: "Samsung",
  price:"$25.000",
  originalPrice: "$30.000",
  description:"Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  amount: 42,
},
{
  id: 2,
  image: cell,
  tittle: "Motorola",
  price:"$31.890",
  originalPrice: "$40.500",
  description:"Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  amount: 20,
},
{
  id: 3,
  image: cell,
  tittle: "Huawei",
  price:"$28.000",
  originalPrice: "$30.000",
  description:"Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  amount: 50,
},
{
  id: 4,
  image: cell,
  tittle: "Xiaomi",
  price:"$50.000",
  originalPrice: "$62.000",
  description:"Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  amount: 37,
},
{
  id: 5,
  image: cell,
  tittle: "Samsung",
  price:"$25.000",
  originalPrice: "$30.000",
  description:"Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  amount: 42,
},
{
  id: 6,
  image: cell,
  tittle: "Motorola",
  price:"$31.890",
  originalPrice: "$40.500",
  description:"Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  amount: 20,
},
{
  id: 7,
  image: cell,
  tittle: "Huawei",
  price:"$28.000",
  originalPrice: "$30.000",
  description:"Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  amount: 50,
},
{
  id: 8,
  image: cell,
  tittle: "Xiaomi",
  price:"$50.000",
  originalPrice: "$62.000",
  description:"Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  amount: 37,
},
{
  id: 9,
  image: cell,
  tittle: "Samsung",
  price:"$25.000",
  originalPrice: "$30.000",
  description:"Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  amount: 42,
},
]

export default product;